apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
 # storageClassName: generic
  accessModes:
  - ReadWriteOnce
  resources:
     limits:
       storage: 1Gi
     requests:
       storage: 1Gi